name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore fs-assignment-2026-2-order-processing-77681.slnx

      - name: Build .NET solution
        run: dotnet build fs-assignment-2026-2-order-processing-77681.slnx --no-restore --configuration Release

  build-react:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admindashboard.react

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build